object Versions {
    const val kotlin: String = "1.6.21"
    const val androidCoreVersion: String = "1.7.0"
    const val composeVersion: String = "1.2.0-rc02"
    const val composeRuntimeVersion: String = "1.2.0-alpha08"
    const val activityComposeVersion = "1.4.0"
    const val navigationComposeVersion = "2.4.2"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val lifecycleVersion = "2.4.1"
    const val retrofitVersion = "2.9.0"
    const val roomVersion = "2.5.0"
    const val hiltVersion = "2.42"
    const val iconsVersion = "eva-icons:1.0.0"
    const val junitVersion = "4.13.2"
    const val espressoVersion = "3.4.0"
    const val jUnitVersion = "1.1.3"
    const val kotlinCompilerExtensionVersion = "1.2.0-rc02"
    const val coroutinesTestVersion = "1.6.1"
    const val archTestingVersion = "2.1.0"
    const val mockitoKotlinVersion = "4.0.0"
    const val mockitoAndroidVersion = "4.3.1"
    const val okHttpVersion = "4.9.3"
    const val picasso = "2.71828"
    const val picassoTransform = "2.4.0"
}
